### ISSUE TITLE
Change simple-git calls to promises

### ISSUE THREAD

**Issue by Pritilender** [weareneopix/daily-log#2]
`simple-git` [has support for promises](https://github.com/steveukx/git-js/issues/103#issuecomment-302137044), so we should do a promise-based rewrite.

**Comment by lazarljubenovic** [comment]
As a side note, _everything_ we have can be moved to promises with [`mz`](https://github.com/normalize/mz).

**Comment by Pritilender** [comment]
As another side note, I believe that `mz` was firstly written in mind with older versions of Node (the issue referenced in Readme is for version 4). The latest node (version 8) includes [utils.promisify](https://nodejs.org/api/util.html#util_util_promisify_original) so I think it's better to go with something that's in the core of the environment then pull a new dependency for doing this.

**Comment by lazarljubenovic** [comment]
Had no idea about this. Absolutely agree, go with core whenever possible.
